

services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: trdatabase
      POSTGRES_USER: my_admin
      POSTGRES_PASSWORD: my_admin
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 5
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      - TZ=Asia/Dubai
    depends_on:
      db:
        condition: service_started
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    

volumes:
  db_data:
